BINDIR = /usr/bin

.PHONY: all
.PHONY: install
.PHONY: uninstall

all:
	@echo "Invalid use of make, please use one of the given options"

install:
	install -m 557 bogoexchange.py $(BINDIR)/bogoexchange

uninstall:
	rm -f $(BINDIR)/bogoexchange
